tunnel: d5271465-64e4-44ef-b031-53285d8da722
credentials-file: /root/.cloudflared/d5271465-64e4-44ef-b031-53285d8da722.json

ingress:
  - hostname: todoist.ssc.one
    service: http://localhost:8766
  - service: http_status:404